# Generated by Django 3.0 on 2021-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_auto_20211028_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('applied', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
